name: build-binary-package

on:
  release:
    types:
    - prereleased

permissions:
  # Use write for: hub release edit
  contents: write

env:
  PROGRAM_NAME: crowdsec-firewall-bouncer

jobs:
  build:
    name: Build and upload all platforms
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: 1.21.9

    - name: Build all platforms
      run: |
        # build platform-all first so the .xz vendor file is not removed
        make platform-all vendor

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        # this will upload the $PROGRAM_NAME-vendor.tar.xz file as well
        gh release upload "$tag_name" $PROGRAM_NAME* vendor.tgz
