name: docker build and push

on:
  merge_group:
  push:
    tags:
      - "v*.*.*"
    branches-ignore:
      - "renovate/**"
      - "dev"
    paths-ignore:
      - "**/renovate.json"
      - ".github/**"
  pull_request:
    paths-ignore:
      - "**/renovate.json"
    branches:
      - "main"
      - "dev"
  workflow_dispatch:
  # schedule:
  # - cron: "0 1 * * 2"

env:
  REGISTRY_IMAGE: yfhme/cs-firewall-bouncer-docker
  TEST_TAG: yfhme/cs-firewall-bouncer-docker:test
  PROGRAM_NAME: crowdsec-firewall-bouncer

jobs:
  build:
    name: Build all platforms
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Check Dir
        run: |
          ls -al

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: '1.22.3'

      - name: Build all platforms
        run: |
          # build platform-all first so the .xz vendor file is not removed
          make platform-all vendor

      - name: Check Dir
        run: |
          ls -al

      - name: Upload Binary to Artifacts
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4
        with:
          name: bin-files
          path: crowdsec-*
          overwrite: true

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: bin-files

      - name: Check Dir
        run: |
          ls -al

      #- name: Get Build Version
      #  run: |
      #    BUILD_VERSION=$(git describe --tags)

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker for test
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: .
          load: true
          #build-args: BUILD_VERSION=$BUILD_VERSION
          tags: ${{ env.TEST_TAG }}

      - name: Test container
        run: |
          docker run --rm --entrypoint crowdsec-firewall-bouncer ${{ env.TEST_TAG }} -version

      - name: Build and push
        if: ${{ github.event_name != 'pull_request' }}
        id: build
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
