name: Static Analysis

on:
  merge_group:
  push:
    branches:
      - dev
    paths:
      - "**.go"
      - "**.js"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "**.go"
      - "**.js"

jobs:
  build:
    name: "golangci-lint + codeql"
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: '1.22.5'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@8214744c546c1e5c8f03dde8fab3a7353211988d # v3
        with:
          languages: go, python

      - name: Build
        run: |
          make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6
        with:
          version: 'v1.58.2'
          args: --issues-exit-code=1 --timeout 10m
          only-new-issues: false
          # the cache is already managed above, enabling it here
          # gives errors when extracting
          skip-cache: true
          skip-save-cache: true

    - name: golangci-lint
      uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6
      with:
        version: v1.59
        args: --issues-exit-code=1 --timeout 10m
        only-new-issues: false
        # the cache is already managed above, enabling it here
        # gives errors when extracting
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@64431c66d0e98a26d34f9485e5f8e317e14956fc
