name: Static Analysis

on:
  merge_group:
  push:
    branches:
      - dev
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - "./renovate.json"
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "docs/**"
      - "./renovate.json"

jobs:
  build:
    name: "golangci-lint + codeql"
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: 1.21.9

      - name: Initialize CodeQL
        uses: github/codeql-action/init@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
        with:
          languages: go, python

      - name: Build
        run: |
          make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4
        with:
          version: v1.57
          args: --issues-exit-code=1 --timeout 10m
          only-new-issues: false
          # the cache is already managed above, enabling it here
          # gives errors when extracting
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
