name: Static Analysis

on:
  merge_group:
  push:
    branches:
      - dev
    paths:
      - "**.go"
      - "**.js"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "**.go"
      - "**.js"

jobs:
  build:
    name: "golangci-lint + codeql"
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22.3'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@d39d31e687223d841ef683f52467bd88e9b21c14 # v3
        with:
          languages: go, python

      - name: Build
        run: |
          make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5
        with:
          version: 'v1.58.2'
          args: --issues-exit-code=1 --timeout 10m
          only-new-issues: false
          # the cache is already managed above, enabling it here
          # gives errors when extracting
          skip-cache: true
          skip-save-cache: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@d39d31e687223d841ef683f52467bd88e9b21c14 # v3
